name: custom
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Commit Message for Deployment
        id: check_message
        run: |
          # Match commit message pattern for deploy - h SERVER_IP - u USER
          if [[ "${{ github.event.head_commit.message }}" =~ deploy\ -\ h\ ([0-9]{1,3}\.){3}[0-9]{1,3}\ -\ u\ [a-zA-Z0-9_]+ ]]; then
            echo "Deployment commit detected. Extracting SERVER_IP and USER..."
            SERVER_IP=$(echo "${{ github.event.head_commit.message }}" | grep -oP "(?<=deploy - h )([0-9]{1,3}\.){3}[0-9]{1,3}")
            USER=$(echo "${{ github.event.head_commit.message }}" | grep -oP "(?<=- u )[a-zA-Z0-9_]+")
            echo "SERVER_IP=${SERVER_IP}" >> $GITHUB_ENV
            echo "SSH_USER=${USER}" >> $GITHUB_ENV
          else
            echo "No valid deployment commit detected. Skipping deployment."
            exit 0
          fi

      - name: Run Setup for Bharat Seva
        if: env.SERVER_IP != '' && env.SSH_USER != ''
        uses: ShubhamRon/setup4bharatseva@main
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ env.SSH_USER }}
          SSH_HOST: ${{ env.SERVER_IP }}
