name: custom
on: push


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vaibhavyadav-dev/setup4bharatseva@main

      - name: CheckCurrent Folder
      - run: |
          echo "Present Directory is "
          cd /home/azureuser/server
          pwd
